// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCduqtJzytzz3n5xuW6uDn0OmscfgykrvQ',
    appId: '1:73554232371:web:cabfecf3d4c7d3ede68f46',
    messagingSenderId: '73554232371',
    projectId: 'proyectomodulo01',
    authDomain: 'proyectomodulo01.firebaseapp.com',
    storageBucket: 'proyectomodulo01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCduqtJzytzz3n5xuW6uDn0OmscfgykrvQ',
    appId: '1:73554232371:android:cabfecf3d4c7d3ede68f46',
    messagingSenderId: '73554232371',
    projectId: 'proyectomodulo01',
    storageBucket: 'proyectomodulo01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'proyectomodulo01',
    storageBucket: 'proyectomodulo01.firebasestorage.app',
    iosBundleId: 'com.example.proyectomodulo01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY',
    appId: 'YOUR_MACOS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'proyectomodulo01',
    storageBucket: 'proyectomodulo01.firebasestorage.app',
    iosBundleId: 'com.example.proyectomodulo01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'YOUR_WINDOWS_API_KEY',
    appId: 'YOUR_WINDOWS_APP_ID',
    messagingSenderId: 'YOUR_MESSAGING_SENDER_ID',
    projectId: 'proyectomodulo01',
    storageBucket: 'proyectomodulo01.firebasestorage.app',
  );
}
