import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Onboard1(),
        ]),
      ),
    );
  }
}

class Onboard1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 375,
          height: 812,
          clipBehavior: Clip.antiAlias,
          decoration: ShapeDecoration(
            color: const Color(0xFF1483C2),
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(20),
            ),
            shadows: [
              BoxShadow(
                color: Color(0x3F000000),
                blurRadius: 50,
                offset: Offset(0, 4),
                spreadRadius: 0,
              )
            ],
          ),
          child: Stack(
            children: [
              Positioned(
                left: 20,
                top: 726,
                child: Container(
                  width: 335,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 335,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(13),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 113.55,
                        top: 13,
                        child: Container(
                          width: 23.10,
                          height: 22,
                          clipBehavior: Clip.antiAlias,
                          decoration: BoxDecoration(),
                        ),
                      ),
                      Positioned(
                        left: 130,
                        top: 17,
                        child: Text(
                          'Get Started',
                          style: TextStyle(
                            color: const Color(0xFF2B2B2B),
                            fontSize: 14,
                            fontFamily: 'Raleway',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
              Positioned(
                left: -162,
                top: 295.20,
                child: Container(
                  transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.35),
                  width: 560.80,
                  height: 420.60,
                  decoration: BoxDecoration(
                    image: DecorationImage(
                      image: NetworkImage("https://placehold.co/561x421"),
                      fit: BoxFit.cover,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 52,
                top: 532,
                child: Container(
                  width: 179,
                  height: 10.71,
                  decoration: ShapeDecoration(
                    color: const Color(0x4C101010),
                    shape: OvalBorder(),
                  ),
                ),
              ),
              Positioned(
                left: 78,
                top: 121,
                child: SizedBox(
                  width: 219,
                  child: Text(
                    'WELLCOME TO\nNIKE',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: const Color(0xFFEBEBEB),
                      fontSize: 30,
                      fontFamily: 'Raleway',
                      fontWeight: FontWeight.w900,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 29,
                top: -3,
                child: Container(
                  width: 316,
                  height: 44,
                  child: Stack(
                    children: [
                      Positioned(
                        left: -11,
                        top: 14,
                        child: SizedBox(
                          width: 54,
                          child: Text(
                            '9:41',
                            textAlign: TextAlign.center,
                            style: TextStyle(
                              color: Colors.white,
                              fontSize: 15,
                              fontFamily: 'Nunito',
                              fontWeight: FontWeight.w700,
                              letterSpacing: -0.30,
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 291.33,
                        top: 17.33,
                        child: Opacity(
                          opacity: 0.35,
                          child: Container(
                            width: 22,
                            height: 11.33,
                            decoration: ShapeDecoration(
                              shape: RoundedRectangleBorder(
                                side: BorderSide(width: 1, color: Colors.white),
                                borderRadius: BorderRadius.circular(2.67),
                              ),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 293.33,
                        top: 19.33,
                        child: Container(
                          width: 18,
                          height: 7.33,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(1.33),
                            ),
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ],
          ),
        ),
      ],
    );
  }
}
/*
import 'package:flutter/material.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'onboard2_screen.dart';

class Onboard1 extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Container(
        width: double.infinity,
        height: double.infinity,
        decoration: BoxDecoration(
          color: const Color(0xFF1483C2),
        ),
        child: Stack(
          children: [
            Positioned(
              left: 20,
              top: 726,
              child: GestureDetector(
                onTap: () {
                  Navigator.push(
                    context,
                    MaterialPageRoute(builder: (context) => Onboard2()),
                  );
                },
                child: Container(
                  width: 335,
                  height: 50,
                  child: Stack(
                    children: [
                      Positioned(
                        left: 0,
                        top: 0,
                        child: Container(
                          width: 335,
                          height: 50,
                          decoration: ShapeDecoration(
                            color: Colors.white,
                            shape: RoundedRectangleBorder(
                              borderRadius: BorderRadius.circular(13),
                            ),
                          ),
                        ),
                      ),
                      Positioned(
                        left: 130,
                        top: 17,
                        child: Text(
                          'Get Started',
                          style: TextStyle(
                            color: const Color(0xFF2B2B2B),
                            fontSize: 14,
                            fontFamily: 'Raleway',
                            fontWeight: FontWeight.w600,
                          ),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
            Positioned(
              left: -162,
              top: 295.20,
              child: Container(
                transform: Matrix4.identity()..translate(0.0, 0.0)..rotateZ(-0.05),
                width: 560.80,
                height: 420.60,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.asset(
                    'assets/images/image3.png',
                    fit: BoxFit.cover,
                  ),
                ),
              ),
            ),
            Positioned(
              left: 52,
              top: 532,
              child: Container(
                width: 179,
                height: 10.71,
                decoration: ShapeDecoration(
                  color: const Color(0x4C101010),
                  shape: OvalBorder(),
                ),
              ),
            ),
            Positioned(
              left: 78,
              top: 121,
              child: SizedBox(
                width: 219,
                child: Text(
                  'WELLCOME TO\nNIKE',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: const Color(0xFFEBEBEB),
                    fontSize: 30,
                    fontFamily: 'Raleway',
                    fontWeight: FontWeight.w900,
                  ),
                ),
              ),
            ),
            Positioned(
              left: 78,
              top: 70,
              child: SvgPicture.asset(
                'assets/images/onboard1.svg',
                width: 219,
                height: 40,
                color: Colors.white,
              ),
            ),
          ],
        ),
      ),
    );
  }
}

 */